-- +goose Up
-- Migration 00003: what the callback API (P02) needs from the schema. Additive only.

-- ---------------------------------------------------------------------------
-- The claim token: a fence, not a credential (P02 D15)
-- ---------------------------------------------------------------------------
-- Generated by the transition core on every claim, replaced on every claim, cleared on every reap
-- and on every move to a state outside the leased set. A runner presents it on every call about a
-- leased ticket, so a reaped runner that shares its service account with its successor cannot act.
ALTER TABLE tickets ADD COLUMN claim_token TEXT;


-- ---------------------------------------------------------------------------
-- Depth is capped at 1 in the database itself (P02 D16)
-- ---------------------------------------------------------------------------
-- A child's parent must be a top-level ticket. `parent_depth` is 0 whenever the ticket has a
-- parent, so the composite foreign key requires the parent row to have depth 0; top-level tickets
-- have a NULL parent_depth and pass (MATCH SIMPLE). This holds against any writer, not only the API.
ALTER TABLE tickets
  ADD COLUMN parent_depth SMALLINT
  GENERATED ALWAYS AS (CASE WHEN parent_ticket_id IS NOT NULL THEN 0::smallint END) STORED;

ALTER TABLE tickets ADD CONSTRAINT tickets_id_depth UNIQUE (id, depth);

ALTER TABLE tickets ADD CONSTRAINT parent_at_depth_0
  FOREIGN KEY (parent_ticket_id, parent_depth) REFERENCES tickets (id, depth);


-- ---------------------------------------------------------------------------
-- api_requests: the request log that makes every mutating call idempotent (P02 D13)
-- ---------------------------------------------------------------------------
-- Keyed on the caller's verified email and the request's Idempotency-Key. The key is claimed in
-- the same transaction as the change it records, and only a success commits: a refused request
-- rolls back and leaves no row. A replay with the same hash returns the stored response; with a
-- different hash it is refused (409). A row with a NULL response is never replayed.
CREATE TABLE api_requests (
  caller        TEXT NOT NULL,          -- verified email of the caller
  request_id    UUID NOT NULL,          -- the Idempotency-Key header
  request_hash  TEXT NOT NULL,          -- sha256 of method, path, body and claim token
  status        SMALLINT,               -- the HTTP status of the stored response
  response      JSONB,                  -- the stored response body
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (caller, request_id)
);
